apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - actualbudget-ingress.yaml
  - argocd-server-ingress.yaml
  - cilium.yaml
  - couchdb-ingress.yaml
  - couchdb-secret.json
  - longhorn-ingress.yaml
  - netbox-ingress.yaml
