apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: actualbudget
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: actualbudget
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    managedNamespaceMetadata:
    automated:
      prune: true
      selfHeal: true
      enabled: true
  project: default
  sources:
    - repoURL: https://community-charts.github.io/helm-charts
      targetRevision: 1.*.*
      helm:
        values: |
          strategy:
            type: Recreate
          files:
            server: /data/server-files
            user: /data/user-files
          persistence:
            enabled: true
            size: 10Gi
            accessModes:
              - ReadWriteOnce
            storageClass: "longhorn"
      chart: actualbudget
