apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: couchdb
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: couchdb
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    managedNamespaceMetadata:
    automated:
      prune: true
      selfHeal: true
      enabled: true
  project: default
  sources:
    - repoURL: https://apache.github.io/couchdb-helm
      targetRevision: 4.6.2
      helm:
        values: |
          image:
            tag: 3.5.0
      chart: couchdb

