apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: couchdb
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: couchdb
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    managedNamespaceMetadata:
    automated:
      prune: true
      selfHeal: true
      enabled: true
  project: default
  sources:
    - repoURL: https://apache.github.io/couchdb-helm
      targetRevision: 4.6.2
      helm:
        values: |
          couchdbConfig:
            couchdb:
              uuid: e721236b54c146849b0d81d3afa0a62a
          persistentVolume:
            enabled: true
          service:
            enabled: true
            type: LoadBalancer
            annotations:
              tailscale.com/expose: "true"
          ingress:
            enabled: true
            hosts: couchdb.goat-locrian.ts.net
          image:
            tag: 3.5.0
      chart: couchdb

