apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: home-assistant
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    managedNamespaceMetadata:
    automated:
      prune: true
      selfHeal: true
      enabled: true
  project: default
  sources:
    - repoURL: http://pajikos.github.io/home-assistant-helm-chart/
      targetRevision: 0.3.*
      helm:
        values: |
          persistance:
            enabled: true
          ingress:
            internal: false
            external: true
          configuration:
            enabled: true
            forceInit: true
            trusted_proxies:
            - 10.224.0.0/16
            templateConfig: |-
              # Loads default set of integrations. Do not remove.
              default_config:

              {{- if .Values.ingress.enabled }}
              http:
                use_x_forwarded_for: true
                trusted_proxies:
                  {{- range .Values.configuration.trusted_proxies }}
                  - {{ . }}
                  {{- end }}
              {{- end}}
              # Load frontend themes from the themes folder
              frontend:
                themes: !include_dir_merge_named themes

              automation: !include automations.yaml
              script: !include scripts.yaml
              scene: !include scenes.yaml
      chart: home-assistant

