apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: home-assistant
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    managedNamespaceMetadata:
    automated:
      prune: true
      selfHeal: true
      enabled: true
  project: default
  sources:
    - repoURL: http://pajikos.github.io/home-assistant-helm-chart/
      targetRevision: 0.3.*
      helm:
        values: |
          persistance:
            enabled: true
          ingress:
            internal: false
            external: true
          configuration:
            enabled: true
            forceInit: true
            trusted_proxies:
              - 10.224.2.0/24
      chart: home-assistant

