apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    automated:
      prune: true
      selfHeal: true
      enabled: true
  project: default
  sources:
    - repoURL: https://charts.longhorn.io/
      targetRevision: v1.10.1
      helm:
        values: |
          defaultSettings:
            defaultReplicaCount: 1
          preUpgradeChecker:
            jobEnabled: false
          service:
            ui:
              type: LoadBalancer
      chart: longhorn

