apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netbox
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: netbox
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    managedNamespaceMetadata:
    automated:
      prune: true
      selfHeal: true
      enabled: true
  project: default
  sources:
    - repoURL: https://charts.netbox.oss.netboxlabs.com/
      targetRevision: 8.3.*
      helm:
        values: |
          postgresql:
            enabled: true
          redis:
            enabled: true
          superuser:
            name: admin
            email: admin@example.com
            password: adminpassword
      chart: netbox
