apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    managedNamespaceMetadata:
    automated:
      prune: true
      selfHeal: true
      enabled: true
  project: default
  sources:
    - repoURL: https://bitnami-labs.github.io/sealed-secrets
      targetRevision: 2.17.9
      chart: couchdb
