apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.com
spec:
  project: default
  source:
    chart: sealed-secrets
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 2.16.1 # Pin to a stable version
    helm:
      releaseName: sealed-secrets
      values: |
        # Optional custom settings
        fullnameOverride: "sealed-secrets-controller"
        
        # Enforce resource boundaries for production stability
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 10m
            memory: 128Mi
  destination:
    server: https://kubernetes.default.svc
    # Conventionally installed in kube-system, or its own namespace
    namespace: kube-system 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
